import type { LucideIcon } from "lucide-react";
import {
  Compass,
  Cpu,
  GraduationCap,
  Heart,
  LayoutGrid,
  MessageCircle,
  PenSquare,
  Search,
  Settings,
  Sparkles,
  UserRound,
  Wrench,
  Zap,
  BadgeCheck,
  ShoppingBag,
} from "lucide-react";

export type CommandGroup = "导航" | "创作与连接" | "学习与工具" | "系统";

export type CommandItem = {
  id: string;
  group: CommandGroup;
  label: string;
  hint?: string;
  href: string;
  keywords: string[];
  Icon: LucideIcon;
};

export const COMMAND_ITEMS: CommandItem[] = [
  {
    id: "home",
    group: "导航",
    label: "发现首页",
    hint: "双列信息流",
    href: "/home",
    keywords: ["feed", "首页", "发现"],
    Icon: Compass,
  },
  {
    id: "me",
    group: "导航",
    label: "我的",
    hint: "账号与快捷入口",
    href: "/me",
    keywords: ["profile", "个人"],
    Icon: UserRound,
  },
  {
    id: "messages",
    group: "导航",
    label: "消息",
    hint: "会话列表 · 未读提醒",
    href: "/messages",
    keywords: ["chat", "im", "私信", "回复"],
    Icon: MessageCircle,
  },
  {
    id: "achievements",
    group: "导航",
    label: "成就墙",
    hint: "徽章与分享卡",
    href: "/me/achievements",
    keywords: ["badge", "成就", "分享"],
    Icon: BadgeCheck,
  },
  {
    id: "search",
    group: "导航",
    label: "全局搜索",
    hint: "标题检索",
    href: "/search",
    keywords: ["find", "检索"],
    Icon: Search,
  },
  {
    id: "publish",
    group: "创作与连接",
    label: "发布笔记",
    href: "/publish",
    keywords: ["写", "发帖", "note"],
    Icon: PenSquare,
  },
  {
    id: "creator",
    group: "创作与连接",
    label: "创作者中心",
    hint: "我的笔记与指标",
    href: "/creator",
    keywords: ["dashboard", "指标", "内容"],
    Icon: BadgeCheck,
  },
  {
    id: "orders",
    group: "学习与工具",
    label: "心愿单与订单",
    href: "/orders",
    keywords: ["wishlist", "订单", "商城"],
    Icon: ShoppingBag,
  },
  {
    id: "match",
    group: "创作与连接",
    label: "创业匹配",
    hint: "画像与推荐",
    href: "/match",
    keywords: ["伙伴", "cofounder", "组队"],
    Icon: Sparkles,
  },
  {
    id: "saved",
    group: "创作与连接",
    label: "我的收藏",
    hint: "已保存的笔记",
    href: "/home?view=saved",
    keywords: ["bookmark", "收藏", "稍后读"],
    Icon: Heart,
  },
  {
    id: "workspace",
    group: "系统",
    label: "工作台",
    hint: "数据看板与快捷能力",
    href: "/workspace",
    keywords: ["dashboard", "看板", "hub"],
    Icon: LayoutGrid,
  },
  {
    id: "learn",
    group: "学习与工具",
    label: "继续学习路线",
    href: "/learn/step/1",
    keywords: ["课程", "路线", "项目"],
    Icon: GraduationCap,
  },
  {
    id: "github",
    group: "学习与工具",
    label: "绑定 GitHub",
    href: "/learn/github",
    keywords: ["仓库", "git"],
    Icon: Zap,
  },
  {
    id: "models",
    group: "学习与工具",
    label: "大模型评分榜",
    hint: "真实体验 · 排行榜 · 讨论",
    href: "/models",
    keywords: ["LLM", "GPT", "Claude", "模型", "榜单", "评分"],
    Icon: Cpu,
  },
  {
    id: "tools",
    group: "学习与工具",
    label: "工具与商城",
    href: "/tools",
    keywords: ["导航", "评分", "模板"],
    Icon: Wrench,
  },
  {
    id: "templates",
    group: "学习与工具",
    label: "模板市场",
    href: "/templates",
    keywords: ["starter", "脚手架", "下载"],
    Icon: Wrench,
  },
  {
    id: "profile-edit",
    group: "系统",
    label: "编辑主页",
    href: "/settings/profile",
    keywords: ["资料", "技能", "profile"],
    Icon: UserRound,
  },
  {
    id: "admin",
    group: "系统",
    label: "账号切换",
    href: "/admin/demo",
    keywords: ["运营", "种子", "人设"],
    Icon: LayoutGrid,
  },
  {
    id: "settings",
    group: "系统",
    label: "设置",
    href: "/settings",
    keywords: ["主题", "退出", "偏好"],
    Icon: Settings,
  },
];
