import type { PrismaClient } from "@prisma/client";
import type { PostType } from "@/lib/domain/postType";
import { DISCOVERY_FEED_TYPES } from "@/lib/domain/discoveryFilters";

type FeedSeed = {
  type: PostType;
  title: string;
  excerpt: string;
  likes: number;
  saves: number;
  tags: string[];
  coverH: number;
  hoursAgo: number;
};

const FEED_SEEDS: FeedSeed[] = [
  {
    type: "NOTE",
    title: "用 Cursor 三天搭出 MVP：我的最小可行流程",
    excerpt: "从 PRD 到可点 demo，只做了三件事：拆任务、写测试清单、每晚复盘。",
    likes: 186,
    saves: 42,
    tags: ["Cursor", "MVP", "独立开发"],
    coverH: 520,
    hoursAgo: 2,
  },
  {
    type: "VIDEO",
    title: "【短视频】出海 SaaS 落地页 A/B 测试实录",
    excerpt: "48 小时改了 3 版 Hero，注册转化从 1.2% 拉到 2.8%。",
    likes: 312,
    saves: 88,
    tags: ["出海", "增长", "A/B"],
    coverH: 640,
    hoursAgo: 5,
  },
  {
    type: "ARTICLE",
    title: "长文：独立开发者如何选择技术合伙人",
    excerpt: "角色互补比「都会写代码」重要，附 7 个面试问题和红线清单。",
    likes: 245,
    saves: 120,
    tags: ["组队", "创业", "合伙人"],
    coverH: 480,
    hoursAgo: 8,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · Glass UI 组件库 v2",
    excerpt: "Tailwind + Radix，支持暗色与动效预设，已在 3 个客户项目落地。",
    likes: 428,
    saves: 156,
    tags: ["设计系统", "开源", "前端"],
    coverH: 560,
    hoursAgo: 12,
  },
  {
    type: "REVIEW",
    title: "工具测评：Claude Code vs Cursor Agent 一周对比",
    excerpt: "同样改一个 Next.js 模块，耗时、diff 质量、回滚成本全记录。",
    likes: 267,
    saves: 95,
    tags: ["Claude", "Cursor", "测评"],
    coverH: 500,
    hoursAgo: 18,
  },
  {
    type: "NOTE",
    title: "小红书冷启动：内容日历模板（可直接抄）",
    excerpt: "把「选题-钩子-CTA」拆成表格，新人第一周就能发满 7 条。",
    likes: 198,
    saves: 210,
    tags: ["运营", "小红书", "冷启动"],
    coverH: 600,
    hoursAgo: 24,
  },
  {
    type: "VIDEO",
    title: "【录屏】Vibe Coding 工作流：从 Figma 到可部署",
    excerpt: "v0 出稿 → Cursor 接 API → Vercel 预览，全程 26 分钟。",
    likes: 156,
    saves: 67,
    tags: ["工作流", "Figma", "部署"],
    coverH: 580,
    hoursAgo: 30,
  },
  {
    type: "ARTICLE",
    title: "长文：AI 编程时代的「产品感」从哪练",
    excerpt: "不是多写 Prompt，而是学会定义验收标准与用户路径。",
    likes: 134,
    saves: 58,
    tags: ["AI编程", "产品", "方法论"],
    coverH: 520,
    hoursAgo: 36,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · 班级管理小程序（期末 A+）",
    excerpt: "Next.js + 小程序云开发，3 人小组 2 周交付。",
    likes: 89,
    saves: 34,
    tags: ["学生项目", "小程序", "案例"],
    coverH: 640,
    hoursAgo: 42,
  },
  {
    type: "REVIEW",
    title: "工具测评：Notion AI 写 PRD 到底省多少时间",
    excerpt: "同一需求写两遍，人工 4h vs AI 辅助 1.5h，附 Prompt。",
    likes: 112,
    saves: 41,
    tags: ["Notion", "PRD", "效率"],
    coverH: 480,
    hoursAgo: 48,
  },
  {
    type: "NOTE",
    title: "找搭子前先把「我能提供什么」写清楚",
    excerpt: "一页纸技能栈 + 时间投入 + 不做什么，匹配效率高一倍。",
    likes: 203,
    saves: 77,
    tags: ["匹配", "组队", "自我介绍"],
    coverH: 540,
    hoursAgo: 54,
  },
  {
    type: "VIDEO",
    title: "【短视频】用 DeepSeek 写后端 API 的踩坑合集",
    excerpt: "鉴权、分页、错误码三件事别交给模型瞎编。",
    likes: 178,
    saves: 52,
    tags: ["DeepSeek", "后端", "踩坑"],
    coverH: 560,
    hoursAgo: 60,
  },
  {
    type: "ARTICLE",
    title: "长文：从 0 到 1 做工具商城的定价实验",
    excerpt: "¥29 / ¥99 / ¥199 三档，最终 ¥99 的 LTV 最好。",
    likes: 221,
    saves: 89,
    tags: ["定价", "工具商城", "变现"],
    coverH: 500,
    hoursAgo: 72,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · LLM 客服知识库（RAG）",
    excerpt: "上传 PDF 自动切片，支持引用溯源，部署在单台 VPS。",
    likes: 356,
    saves: 142,
    tags: ["RAG", "LLM", "B端"],
    coverH: 600,
    hoursAgo: 84,
  },
  {
    type: "REVIEW",
    title: "工具测评：v0 生成的页面能直接上生产吗？",
    excerpt: "好看但 accessibility 和响应式要手改，适合原型不适合终稿。",
    likes: 145,
    saves: 38,
    tags: ["v0", "原型", "前端"],
    coverH: 520,
    hoursAgo: 96,
  },
  {
    type: "NOTE",
    title: "晨间 25 分钟：签到 + 看 3 条热帖的习惯",
    excerpt: "把「发现页」当信息早餐，比刷群聊更聚焦。",
    likes: 67,
    saves: 22,
    tags: ["习惯", "社区", "效率"],
    coverH: 480,
    hoursAgo: 108,
  },
  {
    type: "VIDEO",
    title: "【短视频】招募帖怎么写才有人私信",
    excerpt: "讲清阶段、股权、时间，比「找技术合伙人」有效 10 倍。",
    likes: 192,
    saves: 64,
    tags: ["招募", "组队", "文案"],
    coverH: 620,
    hoursAgo: 120,
  },
  {
    type: "ARTICLE",
    title: "长文：VibeCoding 匹配算法在评什么（通俗版）",
    excerpt: "角色、关键词、方向、预算等七维，不是随便刷人。",
    likes: 288,
    saves: 101,
    tags: ["匹配", "算法", "科普"],
    coverH: 540,
    hoursAgo: 132,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · 出海记账 App（Stripe 已通）",
    excerpt: "多币种、订阅、邮件收据，华人团队面向北美小微商家。",
    likes: 401,
    saves: 167,
    tags: ["出海", "SaaS", "Stripe"],
    coverH: 580,
    hoursAgo: 144,
  },
  {
    type: "REVIEW",
    title: "工具测评：Figma MCP 插件实测",
    excerpt: "设计稿转代码约 70% 可用，组件命名规范很关键。",
    likes: 98,
    saves: 29,
    tags: ["Figma", "MCP", "设计"],
    coverH: 500,
    hoursAgo: 156,
  },
  {
    type: "NOTE",
    title: "今日一人匹配到增长搭子后的 48 小时",
    excerpt: "先对齐北极星指标，再开共享 Notion，避免空聊。",
    likes: 174,
    saves: 55,
    tags: ["匹配", "增长", "复盘"],
    coverH: 560,
    hoursAgo: 168,
  },
  {
    type: "VIDEO",
    title: "【短视频】5 分钟搞懂大模型口碑榜怎么用",
    excerpt: "按编程/写作/性价比筛选，看短评比看参数表靠谱。",
    likes: 133,
    saves: 48,
    tags: ["大模型", "选型", "社区"],
    coverH: 600,
    hoursAgo: 180,
  },
  {
    type: "ARTICLE",
    title: "长文：学生党如何用 Vibe Coding 做第一个付费项目",
    excerpt: "选小痛点、收定金、再写代码，别反过来。",
    likes: 259,
    saves: 118,
    tags: ["学生", "变现", "方法论"],
    coverH: 520,
    hoursAgo: 192,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · 社区团购后台（Vue3）",
    excerpt: "团长端 + 供应商端，日订单 2k+ 的演示数据。",
    likes: 87,
    saves: 31,
    tags: ["Vue", "本地生活", "案例"],
    coverH: 640,
    hoursAgo: 210,
  },
  {
    type: "REVIEW",
    title: "工具测评：GitHub Copilot Workspace 初体验",
    excerpt: "Issue → Plan → PR 链路顺，但复杂 monorepo 仍要人工。",
    likes: 121,
    saves: 44,
    tags: ["Copilot", "GitHub", "测评"],
    coverH: 480,
    hoursAgo: 228,
  },
  {
    type: "NOTE",
    title: "我的发布清单：发笔记前自检 8 项",
    excerpt: "封面、首段钩子、标签、CTA，减少「发了没人看」。",
    likes: 156,
    saves: 72,
    tags: ["发布", "内容", "清单"],
    coverH: 540,
    hoursAgo: 246,
  },
  {
    type: "VIDEO",
    title: "【短视频】双人结对编程直播切片",
    excerpt: "产品写 acceptance criteria，工程按条提交，2 小时合并。",
    likes: 203,
    saves: 61,
    tags: ["结对", "直播", "协作"],
    coverH: 580,
    hoursAgo: 264,
  },
  {
    type: "ARTICLE",
    title: "长文：B 端效率工具如何做第一批种子用户",
    excerpt: "垂直社群 + 模板赠送 + 案例访谈，比投流便宜。",
    likes: 187,
    saves: 83,
    tags: ["B端", "冷启动", "增长"],
    coverH: 500,
    hoursAgo: 288,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · AI 写作助手 Chrome 插件",
    excerpt: "选中即改、语气切换、中英双语，Chrome 商店 4.6 星。",
    likes: 298,
    saves: 109,
    tags: ["插件", "AI写作", "Chrome"],
    coverH: 560,
    hoursAgo: 312,
  },
  {
    type: "REVIEW",
    title: "工具测评：Warp 终端 + AI 命令建议",
    excerpt: "日常 git/docker 省事，复杂 shell 脚本仍需自己审。",
    likes: 76,
    saves: 19,
    tags: ["Warp", "终端", "效率"],
    coverH: 520,
    hoursAgo: 336,
  },
  {
    type: "NOTE",
    title: "周末黑客松：24 小时我们做了什么",
    excerpt: "周六定题、周日 demo，评委最看重「问题是否真」。",
    likes: 142,
    saves: 47,
    tags: ["黑客松", "活动", "复盘"],
    coverH: 600,
    hoursAgo: 360,
  },
  {
    type: "VIDEO",
    title: "【短视频】工具商城上架第一天的数据",
    excerpt: "浏览 800+、下单 12、退款 0，分享定价思路。",
    likes: 165,
    saves: 58,
    tags: ["工具商城", "变现", "数据"],
    coverH: 620,
    hoursAgo: 384,
  },
  {
    type: "ARTICLE",
    title: "长文：技术人如何写好「项目展示」帖",
    excerpt: "结构：痛点 → 方案 → 栈 → 链接 → 招募缺口，附范例。",
    likes: 211,
    saves: 96,
    tags: ["项目展示", "写作", "模板"],
    coverH: 540,
    hoursAgo: 408,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · 智能排班系统（餐饮连锁）",
    excerpt: "多门店、多角色、劳动法规则引擎，PoC 已交付。",
    likes: 134,
    saves: 45,
    tags: ["B端", "餐饮", "排班"],
    coverH: 580,
    hoursAgo: 432,
  },
  {
    type: "REVIEW",
    title: "工具测评：Linear vs Notion 管创业团队任务",
    excerpt: "小团队 Linear 更轻，文档型协作仍选 Notion。",
    likes: 99,
    saves: 33,
    tags: ["Linear", "Notion", "协作"],
    coverH: 480,
    hoursAgo: 456,
  },
  {
    type: "NOTE",
    title: "给女生的 Vibe Coding 入门路线（无代码恐惧版）",
    excerpt: "先改文案再改样式，第一周不碰数据库。",
    likes: 278,
    saves: 134,
    tags: ["入门", "教程", "社区"],
    coverH: 560,
    hoursAgo: 480,
  },
  {
    type: "VIDEO",
    title: "【短视频】一分钟演示匹配页怎么用",
    excerpt: "填画像 → 看分数 → 打招呼，新人也能先聊起来。",
    likes: 188,
    saves: 52,
    tags: ["匹配", "演示", "新手"],
    coverH: 640,
    hoursAgo: 504,
  },
  {
    type: "ARTICLE",
    title: "长文：2026 独立开发者工具栈参考",
    excerpt: "编辑、部署、分析、客服、支付，一套最小组合。",
    likes: 367,
    saves: 178,
    tags: ["工具栈", "独立开发", "年度"],
    coverH: 520,
    hoursAgo: 528,
  },
  {
    type: "SHOWCASE",
    title: "项目展示 · 开源 Markdown 博客主题",
    excerpt: "支持 OG 图、RSS、暗色，GitHub 300+ stars。",
    likes: 223,
    saves: 91,
    tags: ["开源", "博客", "Next.js"],
    coverH: 500,
    hoursAgo: 552,
  },
  {
    type: "REVIEW",
    title: "工具测评：Playwright 做 E2E 值不值得",
    excerpt: "关键路径 5 条就够，别追求 100% 覆盖。",
    likes: 118,
    saves: 40,
    tags: ["Playwright", "测试", "质量"],
    coverH: 540,
    hoursAgo: 576,
  },
];

function authorIdForIndex(i: number): string {
  const n = (i % 24) + 1;
  return `user_seed_${String(n).padStart(2, "0")}`;
}

/** 批量插入发现流种子帖（覆盖 DISCOVERY_FEED_TYPES，支撑瀑布流与分页） */
export async function insertDiscoveryFeedPosts(prisma: PrismaClient) {
  const now = Date.now();
  for (let i = 0; i < FEED_SEEDS.length; i++) {
    const s = FEED_SEEDS[i]!;
    const createdAt = new Date(now - s.hoursAgo * 60 * 60 * 1000);
    const seed = `feed-${i}-${s.type.toLowerCase()}`;
    await prisma.post.create({
      data: {
        authorId: authorIdForIndex(i),
        type: s.type,
        title: s.title,
        excerpt: s.excerpt,
        body: `## ${s.title}\n\n${s.excerpt}\n\n---\n\n（VibeCoding 发现流种子内容，用于演示小红书式双列浏览与无限下拉。）`,
        status: "published",
        coverUrl: `https://picsum.photos/seed/${encodeURIComponent(seed)}/400/${s.coverH}`,
        tags: JSON.stringify(s.tags),
        likes: s.likes,
        saves: s.saves,
        createdAt,
      },
    });
  }

  // 再补一批同类型轮换帖，拉高总量
  const extraCount = 24;
  for (let j = 0; j < extraCount; j++) {
    const type = DISCOVERY_FEED_TYPES[j % DISCOVERY_FEED_TYPES.length]!;
    const createdAt = new Date(now - (600 + j * 12) * 60 * 60 * 1000);
    await prisma.post.create({
      data: {
        authorId: authorIdForIndex(j + FEED_SEEDS.length),
        type,
        title: `社区精选 #${j + 1} · ${type} 类灵感帖`,
        excerpt: "来自 VibeCoding 创业者的真实实践片段，欢迎留言交流。",
        body: "种子帖正文。",
        status: "published",
        coverUrl: `https://picsum.photos/seed/extra-feed-${j}/400/${480 + (j % 5) * 40}`,
        tags: JSON.stringify(["VibeCoding", "社区", type]),
        likes: 15 + ((j * 17) % 180),
        saves: 3 + ((j * 5) % 60),
        createdAt,
      },
    });
  }
}
